# Generated by Django 5.0.1 on 2024-01-16 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tehtek', '0002_rename_accessory_accessories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accessories',
            new_name='Accessorie',
        ),
    ]
